### ISSUE TITLE
「舉」與「擧」都顯示成「擧」了

### ISSUE THREAD

**Issue by sonicgamer0721** [ButTaiwan/genwan-font#4]
請問這個是BUG嗎？

**Comment by sonicgamer0721** [comment]
是這樣的，我自己有把影印版的古書打成電子版，原書中用的是「舉」，我打的也是「舉」，可是用了這個字體，都變成「擧」了。包括你說的「為」與「爲」也是類似情況。這樣就與原書有出入了。

**Comment by ButTaiwan** [comment]
如果是這種需求，比較建議用花園明朝之類刻意收集各種異體的字型。
若有更嚴謹的需求，可能還需要另外檢討方式。（例如像直字，下面是一橫還是Ｌ形，Unicode根本不區分，一般來說字型無法共存兩個寫法。）

而這個系列字型的宗旨是以傳統印刷體（80年代左右常見的鉛字印刷體）字形為準。
確實傳統古書偶爾也會出現「為」字寫法，但鉛字幾乎都是「爲」，所以統一成這個寫法。

**Comment by sonicgamer0721** [comment]
了解了。感謝解答。
