### ISSUE TITLE
請問這個字庫總共有多少字符？是全字庫嗎？

### ISSUE THREAD

**Issue by dzcpy** [ButTaiwan/genwan-font#5]
謝謝！

**Comment by ButTaiwan** [comment]
等於思源宋體有收的所有漢字（再外加台客語漢字補充）。並不到全字庫所有字。

技術上大約是 Adobe-CNS1-7 + Adobe-Japan1-7 + Adobe-KR1-9 + Adobe-GB1-5 的聯集（再加上台客語漢字補充）

**Comment by dzcpy** [comment]
@ButTaiwan 非常感謝解答！
